"""POL game engine constants used by the combat system.

Mirrors the constant definitions from the shard's eScript include files:
- attributes.inc (skill IDs, attribute IDs, vital IDs, caps)
- constants/layers.inc (equipment layers)
- classes.inc (class IDs, bonus constants)
- damages.inc (damage type bitflags)
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# POLCLASS constants — used by .isa() type checking
# ---------------------------------------------------------------------------

POLCLASS_MOBILE = "Mobile"
POLCLASS_NPC = "NPC"
POLCLASS_WEAPON = "Weapon"
POLCLASS_ARMOR = "Armor"
POLCLASS_ITEM = "Item"

# ---------------------------------------------------------------------------
# Equipment layers (from constants/layers.inc)
# ---------------------------------------------------------------------------

LAYER_NONE = 0x00
LAYER_HAND1 = 0x01
LAYER_HAND2 = 0x02
LAYER_SHOES = 0x03
LAYER_PANTS = 0x04
LAYER_SHIRT = 0x05
LAYER_HELM = 0x06
LAYER_GLOVES = 0x07
LAYER_RING = 0x08
LAYER_NECK = 0x0A
LAYER_HAIR = 0x0B
LAYER_WAIST = 0x0C
LAYER_CHEST = 0x0D
LAYER_WRIST = 0x0E
LAYER_BEARD = 0x10
LAYER_TUNIC = 0x11
LAYER_EARS = 0x12
LAYER_ARMS = 0x13
LAYER_CAPE = 0x14
LAYER_PACK = 0x15
LAYER_ROBE = 0x16
LAYER_SKIRT = 0x17
LAYER_LEGS = 0x18
LAYER_MOUNT = 0x19

# ---------------------------------------------------------------------------
# Class IDs (from classes.inc) — stored as ObjProperty keys
# ---------------------------------------------------------------------------

CLASSEID_WARRIOR = "IsWarrior"
CLASSEID_MAGE = "IsMage"
CLASSEID_THIEF = "IsThief"
CLASSEID_RANGER = "IsRanger"
CLASSEID_BARD = "IsBard"
CLASSEID_BLADESINGER = "IsBladesinger"
CLASSEID_PALADIN = "IsPaladin"
CLASSEID_MYSTIC_ARCHER = "IsMysticArcher"
CLASSEID_CRAFTER = "IsCrafter"
CLASSEID_POWERPLAYER = "IsPowerplayer"

ALL_CLASS_IDS: tuple[str, ...] = (
    CLASSEID_WARRIOR,
    CLASSEID_MAGE,
    CLASSEID_THIEF,
    CLASSEID_RANGER,
    CLASSEID_BARD,
    CLASSEID_BLADESINGER,
    CLASSEID_PALADIN,
    CLASSEID_MYSTIC_ARCHER,
    CLASSEID_CRAFTER,
    CLASSEID_POWERPLAYER,
)

# Class bonus constants
CLASSE_BONUS = 1.5
BONUS_PER_LEVEL = 0.25
SMALL_BONUS_PER_LEVEL = 0.15
THIEF_BACKSTAB_BONUS_DAMAGE = 10
THIEF_AMBUSH_BONUS_DAMAGE = 10
RANGER_LEVEL_ARCHERY_RANGE_BONUS = 1
CRAFTER_REPAIR_DIFF_BONUS = 2.5

# ---------------------------------------------------------------------------
# Skill IDs (from attributes.inc)
# ---------------------------------------------------------------------------

SKILLID_ALCHEMY = 0
SKILLID_ANATOMY = 1
SKILLID_ANIMALLORE = 2
SKILLID_ITEMID = 3
SKILLID_ARMSLORE = 4
SKILLID_PARRY = 5
SKILLID_BATTLE_DEFENSE = 5  # alias
SKILLID_BEGGING = 6
SKILLID_BLACKSMITHY = 7
SKILLID_BOWCRAFT = 8
SKILLID_PEACEMAKING = 9
SKILLID_CAMPING = 10
SKILLID_CARPENTRY = 11
SKILLID_CARTOGRAPHY = 12
SKILLID_COOKING = 13
SKILLID_DETECTINGHIDDEN = 14
SKILLID_ENTICEMENT = 15
SKILLID_EVALINT = 16
SKILLID_HEALING = 17
SKILLID_FISHING = 18
SKILLID_FORENSICS = 19
SKILLID_HERDING = 20
SKILLID_HIDING = 21
SKILLID_PROVOCATION = 22
SKILLID_INSCRIPTION = 23
SKILLID_LOCKPICKING = 24
SKILLID_MAGERY = 25
SKILLID_MAGICRESISTANCE = 26
SKILLID_TACTICS = 27
SKILLID_SNOOPING = 28
SKILLID_MUSICIANSHIP = 29
SKILLID_POISONING = 30
SKILLID_ARCHERY = 31
SKILLID_SPIRITSPEAK = 32
SKILLID_STEALING = 33
SKILLID_TAILORING = 34
SKILLID_TAMING = 35
SKILLID_TASTEID = 36
SKILLID_TINKERING = 37
SKILLID_TRACKING = 38
SKILLID_VETERINARY = 39
SKILLID_SWORDSMANSHIP = 40
SKILLID_MACEFIGHTING = 41
SKILLID_FENCING = 42
SKILLID_WRESTLING = 43
SKILLID_LUMBERJACKING = 44
SKILLID_MINING = 45
SKILLID_MEDITATION = 46
SKILLID_STEALTH = 47
SKILLID_REMOVETRAP = 48
SKILLID__HIGHEST = 48

# ---------------------------------------------------------------------------
# Attribute IDs — string names for GetAttribute() calls
# ---------------------------------------------------------------------------

ATTRIBUTEID_STRENGTH = "strength"
ATTRIBUTEID_DEXTERITY = "dexterity"
ATTRIBUTEID_INTELLIGENCE = "intelligence"

ATTRIBUTEID_ALCHEMY = "Alchemy"
ATTRIBUTEID_ANATOMY = "Anatomy"
ATTRIBUTEID_ANIMALLORE = "Animallore"
ATTRIBUTEID_ARCHERY = "Archery"
ATTRIBUTEID_ARMSLORE = "Armslore"
ATTRIBUTEID_BEGGING = "Begging"
ATTRIBUTEID_BLACKSMITHY = "Blacksmithy"
ATTRIBUTEID_BOWCRAFT = "Bowcraft"
ATTRIBUTEID_CAMPING = "Camping"
ATTRIBUTEID_CARPENTRY = "Carpentry"
ATTRIBUTEID_CARTOGRAPHY = "Cartography"
ATTRIBUTEID_COOKING = "Cooking"
ATTRIBUTEID_DETECTINGHIDDEN = "Detectinghidden"
ATTRIBUTEID_ENTICEMENT = "Enticement"
ATTRIBUTEID_EVALINT = "Evaluatingintelligence"
ATTRIBUTEID_FENCING = "Fencing"
ATTRIBUTEID_FISHING = "Fishing"
ATTRIBUTEID_FORENSICS = "Forensicevaluation"
ATTRIBUTEID_HEALING = "Healing"
ATTRIBUTEID_HERDING = "Herding"
ATTRIBUTEID_HIDING = "Hiding"
ATTRIBUTEID_INSCRIPTION = "Inscription"
ATTRIBUTEID_ITEMID = "Itemid"
ATTRIBUTEID_LOCKPICKING = "Lockpicking"
ATTRIBUTEID_LUMBERJACKING = "Lumberjacking"
ATTRIBUTEID_MACEFIGHTING = "Macefighting"
ATTRIBUTEID_MAGERY = "Magery"
ATTRIBUTEID_MAGICRESISTANCE = "Magicresistance"
ATTRIBUTEID_MEDITATION = "Meditation"
ATTRIBUTEID_MINING = "Mining"
ATTRIBUTEID_MUSICIANSHIP = "Musicianship"
ATTRIBUTEID_PARRY = "Parry"
ATTRIBUTEID_PEACEMAKING = "Peacemaking"
ATTRIBUTEID_POISONING = "Poisoning"
ATTRIBUTEID_PROVOCATION = "Provocation"
ATTRIBUTEID_REMOVETRAP = "Removetrap"
ATTRIBUTEID_SNOOPING = "Snooping"
ATTRIBUTEID_SPIRITSPEAK = "Spiritspeak"
ATTRIBUTEID_STEALING = "Stealing"
ATTRIBUTEID_STEALTH = "Stealth"
ATTRIBUTEID_SWORDSMANSHIP = "Swordsmanship"
ATTRIBUTEID_TACTICS = "Tactics"
ATTRIBUTEID_TAILORING = "Tailoring"
ATTRIBUTEID_TAMING = "Animaltaming"
ATTRIBUTEID_TASTEID = "Tasteidentification"
ATTRIBUTEID_TINKERING = "Tinkering"
ATTRIBUTEID_TRACKING = "Tracking"
ATTRIBUTEID_VETERINARY = "Veterinary"
ATTRIBUTEID_WRESTLING = "Wrestling"

# Map skill ID (int) → attribute name (string) for GetAttribute() lookups
SKILLID_TO_ATTRIBUTE: dict[int, str] = {
    SKILLID_ALCHEMY: ATTRIBUTEID_ALCHEMY,
    SKILLID_ANATOMY: ATTRIBUTEID_ANATOMY,
    SKILLID_ANIMALLORE: ATTRIBUTEID_ANIMALLORE,
    SKILLID_ITEMID: ATTRIBUTEID_ITEMID,
    SKILLID_ARMSLORE: ATTRIBUTEID_ARMSLORE,
    SKILLID_PARRY: ATTRIBUTEID_PARRY,
    SKILLID_BEGGING: ATTRIBUTEID_BEGGING,
    SKILLID_BLACKSMITHY: ATTRIBUTEID_BLACKSMITHY,
    SKILLID_BOWCRAFT: ATTRIBUTEID_BOWCRAFT,
    SKILLID_PEACEMAKING: ATTRIBUTEID_PEACEMAKING,
    SKILLID_CAMPING: ATTRIBUTEID_CAMPING,
    SKILLID_CARPENTRY: ATTRIBUTEID_CARPENTRY,
    SKILLID_CARTOGRAPHY: ATTRIBUTEID_CARTOGRAPHY,
    SKILLID_COOKING: ATTRIBUTEID_COOKING,
    SKILLID_DETECTINGHIDDEN: ATTRIBUTEID_DETECTINGHIDDEN,
    SKILLID_ENTICEMENT: ATTRIBUTEID_ENTICEMENT,
    SKILLID_EVALINT: ATTRIBUTEID_EVALINT,
    SKILLID_HEALING: ATTRIBUTEID_HEALING,
    SKILLID_FISHING: ATTRIBUTEID_FISHING,
    SKILLID_FORENSICS: ATTRIBUTEID_FORENSICS,
    SKILLID_HERDING: ATTRIBUTEID_HERDING,
    SKILLID_HIDING: ATTRIBUTEID_HIDING,
    SKILLID_PROVOCATION: ATTRIBUTEID_PROVOCATION,
    SKILLID_INSCRIPTION: ATTRIBUTEID_INSCRIPTION,
    SKILLID_LOCKPICKING: ATTRIBUTEID_LOCKPICKING,
    SKILLID_MAGERY: ATTRIBUTEID_MAGERY,
    SKILLID_MAGICRESISTANCE: ATTRIBUTEID_MAGICRESISTANCE,
    SKILLID_TACTICS: ATTRIBUTEID_TACTICS,
    SKILLID_SNOOPING: ATTRIBUTEID_SNOOPING,
    SKILLID_MUSICIANSHIP: ATTRIBUTEID_MUSICIANSHIP,
    SKILLID_POISONING: ATTRIBUTEID_POISONING,
    SKILLID_ARCHERY: ATTRIBUTEID_ARCHERY,
    SKILLID_SPIRITSPEAK: ATTRIBUTEID_SPIRITSPEAK,
    SKILLID_STEALING: ATTRIBUTEID_STEALING,
    SKILLID_TAILORING: ATTRIBUTEID_TAILORING,
    SKILLID_TAMING: ATTRIBUTEID_TAMING,
    SKILLID_TASTEID: ATTRIBUTEID_TASTEID,
    SKILLID_TINKERING: ATTRIBUTEID_TINKERING,
    SKILLID_TRACKING: ATTRIBUTEID_TRACKING,
    SKILLID_VETERINARY: ATTRIBUTEID_VETERINARY,
    SKILLID_SWORDSMANSHIP: ATTRIBUTEID_SWORDSMANSHIP,
    SKILLID_MACEFIGHTING: ATTRIBUTEID_MACEFIGHTING,
    SKILLID_FENCING: ATTRIBUTEID_FENCING,
    SKILLID_WRESTLING: ATTRIBUTEID_WRESTLING,
    SKILLID_LUMBERJACKING: ATTRIBUTEID_LUMBERJACKING,
    SKILLID_MINING: ATTRIBUTEID_MINING,
    SKILLID_MEDITATION: ATTRIBUTEID_MEDITATION,
    SKILLID_STEALTH: ATTRIBUTEID_STEALTH,
    SKILLID_REMOVETRAP: ATTRIBUTEID_REMOVETRAP,
}

# Reverse map: attribute name (lowercased) → skill ID
ATTRIBUTE_TO_SKILLID: dict[str, int] = {
    v.lower(): k for k, v in SKILLID_TO_ATTRIBUTE.items()
}

# ---------------------------------------------------------------------------
# Vital IDs
# ---------------------------------------------------------------------------

VITALID_LIFE = "life"
VITALID_MANA = "mana"
VITALID_STAMINA = "stamina"

# Caps
SKILL_STAT_CAP = 130
BASE_CAP = 1300

# ---------------------------------------------------------------------------
# Damage type bitflags (from damages.inc)
# ---------------------------------------------------------------------------

DMGID_FIRE = 0x0001
DMGID_AIR = 0x0002
DMGID_EARTH = 0x0004
DMGID_WATER = 0x0008
DMGID_NECRO = 0x0010
DMGID_HOLY = 0x0020
DMGID_POISON = 0x0040
DMGID_ACID = 0x0080
DMGID_PHYSICAL = 0x0100
DMGID_MAGIC = 0x0200
DMGID_ASTRAL = 0x0400
DMGID_NO_RESIST = 0x0800
