/////////////////////////////////////////////////////////////////////
// CmdLevel.inc
//
// Contain the command level names
/////////////////////////////////////////////////////////////////////


const CMDLEVEL_PLAYER		:= 0;
const CMDLEVEL_COUNSELOR	:= 1;
const CMDLEVEL_SHARD_MOM	:= 2;
const CMDLEVEL_SEER		:= 3;
const CMDLEVEL_GAME_MASTER	:= 4;
const CMDLEVEL_ADMINISTRATOR	:= 5;
const CMDLEVEL_DEVELOPER	:= 6;
